"""Initial migration with multi-tenant

Revision ID: 10651a6d92bd
Revises:
Create Date: 2026-03-01 11:33:28.617462

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10651a6d92bd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_name"), "tenants", ["name"], unique=True)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_table(
        "pricing_context_schemas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "schema_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pricing_context_schemas_name"),
        "pricing_context_schemas",
        ["name"],
        unique=False,
    )
    op.create_table(
        "pricing_schemes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("urn", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pricing_schemes_urn"), "pricing_schemes", ["urn"], unique=True
    )
    op.create_table(
        "pricing_rule_identities",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("scheme_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fee_type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scheme_id"],
            ["pricing_schemes.id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "pricing_rule_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_uuid", sa.UUID(), nullable=False),
        sa.Column("schema_id", sa.UUID(), nullable=False),
        sa.Column(
            "logica_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("vigencia", postgresql.DATERANGE(), nullable=False),
        sa.Column("hash_firma", sa.String(), nullable=True),
        sa.Column("hash_algoritmo", sa.String(length=20), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("rule_uuid"), "="),
            (sa.column("vigencia"), "&&"),
            using="gist",
            name="no_solapamiento_temporal_pricing",
        ),
        sa.ForeignKeyConstraint(
            ["rule_uuid"],
            ["pricing_rule_identities.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["pricing_context_schemas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pricing_rule_versions")
    op.drop_table("pricing_rule_identities")
    op.drop_index(op.f("ix_pricing_schemes_urn"), table_name="pricing_schemes")
    op.drop_table("pricing_schemes")
    op.drop_index(
        op.f("ix_pricing_context_schemas_name"), table_name="pricing_context_schemas"
    )
    op.drop_table("pricing_context_schemas")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_tenants_name"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
