"""compliance_hardening

Revision ID: 39a41920ba4d
Revises: af7ea7eee11c
Create Date: 2026-02-25 17:22:44.684377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39a41920ba4d'
down_revision: Union[str, Sequence[str], None] = 'af7ea7eee11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglas_identidad',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('clave_interna', sa.String(), nullable=False),
    sa.Column('nombre_humano', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_reglas_identidad_clave_interna'), 'reglas_identidad', ['clave_interna'], unique=True)
    op.create_table('reglas_versiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regla_uuid', sa.UUID(), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('severidad', postgresql.ENUM('INFO', 'WARNING', 'ERROR', 'BLOCKER', name='severidad_regla'), nullable=False),
    sa.Column('tipo', postgresql.ENUM('OBLIGATORIA', 'SUGERENCIA', 'CALCULO', name='tipo_regla'), nullable=False),
    sa.Column('logica_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_error', sa.String(), nullable=False),
    sa.Column('vigencia', postgresql.DATERANGE(), nullable=False),
    postgresql.ExcludeConstraint((sa.column('regla_uuid'), '='), (sa.column('vigencia'), '&&'), using='gist', name='evitar_solapamiento_reglas'),
    sa.ForeignKeyConstraint(['regla_uuid'], ['reglas_identidad.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reglas_compliance')
    op.alter_column('normas', 'metadata_norma',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.add_column('versiones_contenido', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    # === DB HARDENING (AUDITORIA Y GIST) ===
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
    op.execute("CREATE INDEX IF NOT EXISTS idx_vigencia_contenido ON versiones_contenido USING GIST (unidad_uuid, vigencia);")
    op.execute("""
    CREATE TABLE patch_logs (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        decreto_fuente_url TEXT,
        patch_candidate_json JSONB NOT NULL,
        prompt_usado TEXT,
        confidence_score FLOAT,
        aplicado_por UUID,
        aplicado_en TIMESTAMP DEFAULT NOW(),
        estado VARCHAR(20),
        hash_resultado CHAR(64)
    );
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # === DB HARDENING REVERT ===
    op.execute("DROP TABLE IF EXISTS patch_logs;")
    op.execute("DROP INDEX IF EXISTS idx_vigencia_contenido;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('versiones_contenido', 'deleted_at')
    op.alter_column('normas', 'metadata_norma',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_table('reglas_compliance',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre_regla', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('logica_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versiones_contenido.id'], name=op.f('reglas_compliance_version_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reglas_compliance_pkey'))
    )
    op.drop_table('reglas_versiones')
    op.drop_index(op.f('ix_reglas_identidad_clave_interna'), table_name='reglas_identidad')
    op.drop_table('reglas_identidad')
    # === DB HARDENING REVERT ===
    op.execute("DROP TYPE IF EXISTS severidad_regla;")
    op.execute("DROP TYPE IF EXISTS tipo_regla;")
    # ### end Alembic commands ###
