[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
siwe = "0.6" # SIWE verification
hex = "0.4"
sha2 = "0.10"
time = "0.3"
jsonlogic-fast = { path = "../core" }
lambda_http = "0.13"
aws-config = { version = "1.5", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.30"
aws-sdk-secretsmanager = "1.30"
alloy = { version = "2.1.0", features = ["full", "reqwest", "providers"] }
alloy-primitives = { version = "1.6" }
futures-util = "0.3.32"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2.0"
tower-http = { version = "0.7.0", features = ["cors", "limit", "trace"] }
tower = "0.5.3"

[[bin]]
name = "api_server"
path = "src/bin/api_server.rs"

[[bin]]
name = "lambda"
path = "src/bin/lambda.rs"

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
http-body-util = "0.1.3"
k256 = { version = "0.13.4", features = ["ecdsa"] }
sha3 = "0.10.9"
rand = "0.8.6"
siwe = "0.6"
